name: Delete Old Branches

on:
  workflow_dispatch:

jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --prune --tags

      - name: List branches and timestamps
        run: |
          today=$(date -u +"%Y-%m-%d")
          thirty_days_ago=$(date -u -d "$today -30 days" +"%Y-%m-%d")
          git for-each-ref --sort=committerdate --format="%(committerdate:short) %(refname:short)" refs/heads/* |
          while read -r branch_date branch_name; do
            branch_timestamp=$(date -u -d "$branch_date" +%s)
            thirty_days_ago_timestamp=$(date -u -d "$thirty_days_ago" +%s)
            if [ "$branch_timestamp" -lt "$thirty_days_ago_timestamp" ]; then
              echo "Deleting branch $branch_name"
              git push origin --delete "$branch_name"
            else
              echo "Branch $branch_name is not old enough to delete"
            fi
          done
