name: Repo cleanup (old PRs, branches and issues)

on:
  schedule:
    - cron: "12 14 * * *"

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  cleanup-repository:
    runs-on: ubuntu-latest

    steps:
      - name: Delete old branches
        env:

      # Add your existing code lines 16 to 26 here
          github_token: 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
          last_commit_age_days: 30
          dry_run: no
          ignore_branches: master,main,staging,development,production
