name: semantic-release

on:
  push:
    branches:
      - production

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - run: npm install --no-save

      # Find the commit hash where the feature branch diverged from production
      - name: Find commit hash
        run: |
          commit_hash=$(git merge-base HEAD production)
          echo "::set-output name=commit_hash::$commit_hash"

      # Check commit messages using the commit hash as reference
      - name: Check commit messages
        run: npx commitlint --from=${{ steps.find_commit_hash.outputs.commit_hash }}

      - run: npx semantic-release

