name: Validate Branch Name

on:
  pull_request:
    branches:
      - 'production'

jobs:
  check_branch_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug information
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "BRANCH_NAME: ${GITHUB_REF#refs/heads/}"

      - name: Fail if branch name does not match pattern
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          DATE_PATTERN='^hotfix\/(0[1-9]|1[0-2])_(0[1-9]|1[0-9]|2[0-9]|3[0-1])_[0-9]{2}$'
          if [[ ! $BRANCH_NAME =~ $DATE_PATTERN ]]; then
            echo "Error: Invalid branch name! Branch names for hotfixes should match 'hotfix/DD_MM_YY'."
            exit 1
          fi
