name: Delete Old Branches

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  delete_branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete old branches
        run: |
          git fetch --prune
          git branch -r --format='%(refname:short) %(committerdate:short)' | awk '$2 < "'$(date -d '30 days ago' +'%Y-%m-%d')'" && !/^(main|master|development|staging|production)$/{print $1}' | xargs -I {} git push origin --delete {}
