name: Validate Branch Name

on:
  pull_request:
    branches:
      - 'production'

jobs:
  check_branch_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fail if branch name does not match pattern
        run: |
          BRANCH_NAME= github.event.pull_request.base.ref
          echo $BRANCH_NAME
          DATE_PATTERN='^hotfix\/[0-9]{2}_[0-9]{2}_[0-9]{4}$'
          if [[ ! $BRANCH_NAME =~ $DATE_PATTERN ]]; then
            echo "Error: Invalid branch name! Branch names for hotfixes should match 'hotfix/DD_MM_YYYY'."
            exit 1
          fi
