name: Disable Merge for Invalid PRs

on:
  pull_request:
    branches:
      - 'production'

jobs:
  check_branch_name:
    runs-on: ubuntu-latest

    steps:
      - name: Check Branch Name
        id: branch-check
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          DATE_PATTERN='^hotfix\/(0[1-9]|1[0-2])_(0[1-9]|1[0-9]|2[0-9]|3[0-1])_[0-9]{2}$'

          if [[ $BRANCH_NAME =~ $DATE_PATTERN ]]; then
            echo "::set-output name=is_valid::true"
          else
            echo "::set-output name=is_valid::false"
          fi

      - name: Disable Merge for Invalid Branches
        if: steps.branch-check.outputs.is_valid == 'false'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;

            github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              state: 'closed'
            });

            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: 'Error: Invalid branch name! Branch names for hotfixes should match "hotfix/DD_MM_YY".'
            });
