name: Validate Branch Name

on:
  pull_request:
    branches:
      - 'production'

jobs:
  check_branch_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fail if branch name does not match pattern
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          DATE_PATTERN='/hotfix\/\d{2}_\d{2}_\d{4}/gm'
          if [[ ! $BRANCH_NAME =~ $DATE_PATTERN ]]; then
            echo "Error: Invalid branch name! Branch names for hotfixes should match 'hotfix/DD_MM_YY'."
            exit 1
          fi

     
